services:
  data:
    build:
      context: ./data
    container_name: data
    networks:
      - topo-net
  web:
    build:
      context: ./web
    container_name: web
    networks:
      - topo-net
    ports:
      # <Extern>:<Intern>
      - 8181:8181
  db:
    image: mariadb:latest
    container_name: db
    ports:
      # <Extern>:<Intern>
      - 3307:3306
    environment:
      - MARIADB_USER=www-data
      - MARIADB_PASSWORD=password123
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=topology-tool
    command: --default-storage-engine innodb
#      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - topo-net
networks:
  topo-net:
    driver: bridge
