services:
  data:
    build: data
    image: python
    container_name: data
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: mariadb:latest
    container_name: db
    ports:
      # <Extern>:<Intern>
      - 3307:3306
    environment:
      - MARIADB_USER=www-data
      - MARIADB_PASSWORD=db_pwd
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=topo-tool
    command: --default-storage-engine innodb
    healthcheck:
      test: [ "CMD","mysql","-f","http://localhost:3306" ]
      interval: 1s
      timeout: 1s
      retries: 5

