services:
  data:
    build: .
    image: python
    container_name: topo-tool_data
    depends_on:
      - db
  db:
    build: data/db
    image: mariadb/server:latest
    container_name: topo-tool_db
    ports:
      # <Extern>:<Intern>
      - 3307:3306
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=topo-tool
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:3306" ]
      interval: 15s
      timeout: 3s
      retries: 5