services:
  db:
    image: mariadb:latest
    container_name: topo-tool_db
    ports:
      # <Extern>:<Intern>
      - 3307:3306
    environment:
      - MARIADB_USER=www-data
      - MARIADB_PASSWORD=db_pwd
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=topo-tool
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:3306" ]
      interval: 15s
      timeout: 3s
      retries: 5
  data:
    build: data
    image: python
    container_name: topo-tool_data
    depends_on:
      - db
